//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Presentation.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ValidationMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Presentation.Resources.ValidationMessages", typeof(ValidationMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Cpf ou Cpnj é obrigatório.
        /// </summary>
        public static string CpfCnpjRequired {
            get {
                return ResourceManager.GetString("CpfCnpjRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Data de Nascimento é obrigatória.
        /// </summary>
        public static string DataNascimentoRequired {
            get {
                return ResourceManager.GetString("DataNascimentoRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Ddd deve conter 2(dois) caracteres.
        /// </summary>
        public static string DddInvalid {
            get {
                return ResourceManager.GetString("DddInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Ddd é obrigatório.
        /// </summary>
        public static string DddRequired {
            get {
                return ResourceManager.GetString("DddRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Email informado não é válido.
        /// </summary>
        public static string EmailInvalid {
            get {
                return ResourceManager.GetString("EmailInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Email é obrigatório.
        /// </summary>
        public static string EmailRequired {
            get {
                return ResourceManager.GetString("EmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Confirmação de Senha não é igual a primeira senha informada.
        /// </summary>
        public static string PasswordConfirmCompare {
            get {
                return ResourceManager.GetString("PasswordConfirmCompare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Confirmação de Senha é obrigatória.
        /// </summary>
        public static string PasswordConfirmRequired {
            get {
                return ResourceManager.GetString("PasswordConfirmRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Senha precisa conter letras, números, pelo menos 1(um) caractere menúsculo e 1(um) maiúsculo.
        /// </summary>
        public static string PasswordInvalid {
            get {
                return ResourceManager.GetString("PasswordInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Senha precisa ter no mínimo 6 caracteres.
        /// </summary>
        public static string PasswordInvlidLength {
            get {
                return ResourceManager.GetString("PasswordInvlidLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Senha é obrigatória.
        /// </summary>
        public static string PasswordRequired {
            get {
                return ResourceManager.GetString("PasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O telefone deve conter 8(oito) ou 9(nove) números.
        /// </summary>
        public static string TefoneInvalid {
            get {
                return ResourceManager.GetString("TefoneInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Telefone é obrigatório.
        /// </summary>
        public static string TelefoneRequired {
            get {
                return ResourceManager.GetString("TelefoneRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Nome de Usuário deve conter apenas letras.
        /// </summary>
        public static string UserNameInvalid {
            get {
                return ResourceManager.GetString("UserNameInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Nome de Usuário deve conter de 4 a 10 caracteres.
        /// </summary>
        public static string UserNameInvalidLength {
            get {
                return ResourceManager.GetString("UserNameInvalidLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Nome de Usuário é obrigatório.
        /// </summary>
        public static string UserNameRequired {
            get {
                return ResourceManager.GetString("UserNameRequired", resourceCulture);
            }
        }
    }
}
